#!/usr/bin/env node
/**
 * Extracts the popup's user-visible copy into data/strings.json.
 *
 * Why this exists: the same sentence was written in two files. "Upload Image
 * you want to replace everything with" lived in popup.html and again in
 * popup.js, and both button captions lived in the HTML and in the JS that
 * swapped them. Editing one and forgetting the other was a bug waiting to
 * happen, and the strings are long enough that retyping them invites a
 * silent mismatch.
 *
 * This reads both originals at a pinned revision, collapses the duplicates,
 * and fails if it meets a string it has no key for. Nothing is typed twice
 * and nothing can be quietly dropped.
 *
 * Usage: node tools/extract-strings.mjs [--check]
 *   --check exits non-zero if data/strings.json is stale instead of rewriting.
 */

import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

/** Last revision containing the pre-refactor popup files, byte for byte. */
const SOURCE_REV = "aea34c3";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUTPUT = join(ROOT, "data", "strings.json");

/**
 * Maps the literal copy to its key. Keyed by the string itself, so the three
 * sentences that appeared in both files collapse to one entry automatically.
 */
const KEYS = new Map([
  ["Text Replacer", "documentTitle"],
  ["Text and Image Replacer", "appTitle"],
  ["Enter text you want to replace everything with", "replacementTextPlaceholder"],
  ["Upload Image you want to replace everything with", "uploadPrompt"],
  ["Image Uploaded - Click To Upload Another", "uploadPromptAfterUpload"],
  ["Uploaded Image", "imagePreviewLabel"],
  ["Start Replacing Text + Images", "startButton"],
  ["Stop Replacing Text + Images", "stopButton"],
]);

/** Places copy can hide in the original markup. */
const HTML_PATTERNS = [
  /<title>([^<]+)<\/title>/g,
  /<h1>([^<]+)<\/h1>/g,
  /placeholder="([^"]+)"/g,
  /alt="([^"]+)"/g,
  /<span[^>]*>([^<]+)<\/span>/g,
  /<button[^>]*>([^<]+)<\/button>/g,
];

function read(file) {
  return execFileSync("git", ["show", `${SOURCE_REV}:${file}`], { cwd: ROOT, encoding: "utf8" });
}

/** Every quoted literal on a line that assigns to textContent. */
function copyFromScript(js) {
  const found = [];
  for (const line of js.split("\n")) {
    if (!line.includes(".textContent")) continue;
    for (const match of line.matchAll(/'([^']*)'|"([^"]*)"/g)) {
      found.push(match[1] ?? match[2]);
    }
  }
  return found;
}

function copyFromMarkup(html) {
  const found = [];
  for (const pattern of HTML_PATTERNS) {
    for (const match of html.matchAll(pattern)) found.push(match[1].trim());
  }
  return found;
}

function build() {
  const found = [...copyFromMarkup(read("popup.html")), ...copyFromScript(read("popup.js"))];

  const strings = {};
  for (const text of found) {
    const key = KEYS.get(text);
    if (!key) throw new Error(`no key mapped for copy: ${JSON.stringify(text)}`);
    if (key in strings && strings[key] !== text) {
      throw new Error(`key ${key} maps to two different strings`);
    }
    strings[key] = text;
  }

  const missing = [...KEYS.values()].filter((key) => !(key in strings));
  if (missing.length) throw new Error(`keys declared but never found: ${missing.join(", ")}`);

  const sorted = {};
  for (const key of Object.keys(strings).sort()) sorted[key] = strings[key];

  return {
    _comment: `Generated by tools/extract-strings.mjs from popup.html and popup.js at ${SOURCE_REV}. Every visible word in the popup comes from here; edit this file to reword the UI.`,
    ...sorted,
  };
}

const json = `${JSON.stringify(build(), null, 2)}\n`;

if (process.argv.includes("--check")) {
  if (readFileSync(OUTPUT, "utf8") !== json) {
    console.error("data/strings.json is stale, re-run: node tools/extract-strings.mjs");
    process.exit(1);
  }
  console.log("data/strings.json matches the extracted source");
} else {
  writeFileSync(OUTPUT, json);
  console.log(`wrote ${OUTPUT}`);
}
